FROM yiluxiangbei/centos7-bigdata-datax

RUN mkdir -p /home/datax-web
RUN mkdir -p /home/datax-web/data/applogs/admin

COPY ./datax-admin-2.1.2.jar /home/datax-web/datax-admin.jar

WORKDIR /home/datax-web

COPY application-admin.yml /home/datax-web/application.yml
COPY logback-admin.xml /home/datax-web/logback.xml
COPY i18n /home/datax-web/i18n
COPY mybatis-mapper /home/datax-web/mybatis-mapper

ENV CLASSPATH /home/datax-web:$CLASSPATH

ARG DATA_PATH=./data
ARG SERVER_PORT=8080
ARG DB_USERNAME=root
ARG DB_PASSWORD=root
ARG DB_HOST=datax-web-mysql
ARG DB_PORT=3306
ARG DB_DATABASE=dataxweb
#先阶段只支持qq邮箱
ARG MAIL_USERNAME=username
ARG MAIL_PASSWORD=password
ENV SERVER_PORT=${SERVER_PORT} \
    DB_USERNAME=${DB_USERNAME} \
    DB_PASSWORD=${DB_PASSWORD} \
    DB_HOST=${DB_HOST} \
    DB_PORT=${DB_PORT} \
    DB_DATABASE=${DB_DATABASE} \
    MAIL_USERNAME=${MAIL_USERNAME} \
    MAIL_PASSWORD=${MAIL_PASSWORD} \
    DATA_PATH=${DATA_PATH}:.

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","datax-admin.jar"]