FROM yiluxiangbei/centos7-bigdata-datax

RUN mkdir -p /home/datax-web
RUN mkdir -p /home/datax-web/data/applogs/executor/jobhandler

COPY ./datax-executor-2.1.2.jar /home/datax-web/datax-executor.jar

WORKDIR /home/datax-web

COPY application-executor.yml /home/datax-web/application.yml
COPY logback-executor.xml /home/datax-web/logback.xml

ENV CLASSPATH /home/datax-web:$CLASSPATH

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","datax-executor.jar"]